name: remote ssh command
on: 
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - .github
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /usr/local/map-tile-server
          git pull
          docker-compose down
          docker-compose up -d --build
